/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RetailersIndexRouteImport } from './routes/retailers.index'
import { Route as FormsIndexRouteImport } from './routes/forms.index'
import { Route as RetailersRetailerIdRouteImport } from './routes/retailers.$retailerId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as SettingsWorkflowManagerWorkflowIdRouteImport } from './routes/settings.workflow-manager.$workflowId'
import { Route as FormsPreviewFormIdRouteImport } from './routes/forms.preview.$formId'
import { Route as FormsFillFormSlugRouteImport } from './routes/forms.fill.$formSlug'
import { Route as FormsBuilderFormIdRouteImport } from './routes/forms.builder.$formId'
import { Route as FormsFormIdSubmissionsRouteImport } from './routes/forms.$formId.submissions'
import { Route as FormsFormIdShareRouteImport } from './routes/forms.$formId.share'
import { Route as FormsFormIdAnalyticsRouteImport } from './routes/forms.$formId.analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailersIndexRoute = RetailersIndexRouteImport.update({
  id: '/retailers/',
  path: '/retailers/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailersRetailerIdRoute = RetailersRetailerIdRouteImport.update({
  id: '/retailers/$retailerId',
  path: '/retailers/$retailerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWorkflowManagerWorkflowIdRoute =
  SettingsWorkflowManagerWorkflowIdRouteImport.update({
    id: '/settings/workflow-manager/$workflowId',
    path: '/settings/workflow-manager/$workflowId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormsPreviewFormIdRoute = FormsPreviewFormIdRouteImport.update({
  id: '/forms/preview/$formId',
  path: '/forms/preview/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFillFormSlugRoute = FormsFillFormSlugRouteImport.update({
  id: '/forms/fill/$formSlug',
  path: '/forms/fill/$formSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsBuilderFormIdRoute = FormsBuilderFormIdRouteImport.update({
  id: '/forms/builder/$formId',
  path: '/forms/builder/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdSubmissionsRoute = FormsFormIdSubmissionsRouteImport.update({
  id: '/forms/$formId/submissions',
  path: '/forms/$formId/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdShareRoute = FormsFormIdShareRouteImport.update({
  id: '/forms/$formId/share',
  path: '/forms/$formId/share',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdAnalyticsRoute = FormsFormIdAnalyticsRouteImport.update({
  id: '/forms/$formId/analytics',
  path: '/forms/$formId/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/retailers/$retailerId': typeof RetailersRetailerIdRoute
  '/forms/': typeof FormsIndexRoute
  '/retailers/': typeof RetailersIndexRoute
  '/forms/$formId/analytics': typeof FormsFormIdAnalyticsRoute
  '/forms/$formId/share': typeof FormsFormIdShareRoute
  '/forms/$formId/submissions': typeof FormsFormIdSubmissionsRoute
  '/forms/builder/$formId': typeof FormsBuilderFormIdRoute
  '/forms/fill/$formSlug': typeof FormsFillFormSlugRoute
  '/forms/preview/$formId': typeof FormsPreviewFormIdRoute
  '/settings/workflow-manager/$workflowId': typeof SettingsWorkflowManagerWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/retailers/$retailerId': typeof RetailersRetailerIdRoute
  '/forms': typeof FormsIndexRoute
  '/retailers': typeof RetailersIndexRoute
  '/forms/$formId/analytics': typeof FormsFormIdAnalyticsRoute
  '/forms/$formId/share': typeof FormsFormIdShareRoute
  '/forms/$formId/submissions': typeof FormsFormIdSubmissionsRoute
  '/forms/builder/$formId': typeof FormsBuilderFormIdRoute
  '/forms/fill/$formSlug': typeof FormsFillFormSlugRoute
  '/forms/preview/$formId': typeof FormsPreviewFormIdRoute
  '/settings/workflow-manager/$workflowId': typeof SettingsWorkflowManagerWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/retailers/$retailerId': typeof RetailersRetailerIdRoute
  '/forms/': typeof FormsIndexRoute
  '/retailers/': typeof RetailersIndexRoute
  '/forms/$formId/analytics': typeof FormsFormIdAnalyticsRoute
  '/forms/$formId/share': typeof FormsFormIdShareRoute
  '/forms/$formId/submissions': typeof FormsFormIdSubmissionsRoute
  '/forms/builder/$formId': typeof FormsBuilderFormIdRoute
  '/forms/fill/$formSlug': typeof FormsFillFormSlugRoute
  '/forms/preview/$formId': typeof FormsPreviewFormIdRoute
  '/settings/workflow-manager/$workflowId': typeof SettingsWorkflowManagerWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers/$customerId'
    | '/retailers/$retailerId'
    | '/forms/'
    | '/retailers/'
    | '/forms/$formId/analytics'
    | '/forms/$formId/share'
    | '/forms/$formId/submissions'
    | '/forms/builder/$formId'
    | '/forms/fill/$formSlug'
    | '/forms/preview/$formId'
    | '/settings/workflow-manager/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers/$customerId'
    | '/retailers/$retailerId'
    | '/forms'
    | '/retailers'
    | '/forms/$formId/analytics'
    | '/forms/$formId/share'
    | '/forms/$formId/submissions'
    | '/forms/builder/$formId'
    | '/forms/fill/$formSlug'
    | '/forms/preview/$formId'
    | '/settings/workflow-manager/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/customers/$customerId'
    | '/retailers/$retailerId'
    | '/forms/'
    | '/retailers/'
    | '/forms/$formId/analytics'
    | '/forms/$formId/share'
    | '/forms/$formId/submissions'
    | '/forms/builder/$formId'
    | '/forms/fill/$formSlug'
    | '/forms/preview/$formId'
    | '/settings/workflow-manager/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  RetailersRetailerIdRoute: typeof RetailersRetailerIdRoute
  FormsIndexRoute: typeof FormsIndexRoute
  RetailersIndexRoute: typeof RetailersIndexRoute
  FormsFormIdAnalyticsRoute: typeof FormsFormIdAnalyticsRoute
  FormsFormIdShareRoute: typeof FormsFormIdShareRoute
  FormsFormIdSubmissionsRoute: typeof FormsFormIdSubmissionsRoute
  FormsBuilderFormIdRoute: typeof FormsBuilderFormIdRoute
  FormsFillFormSlugRoute: typeof FormsFillFormSlugRoute
  FormsPreviewFormIdRoute: typeof FormsPreviewFormIdRoute
  SettingsWorkflowManagerWorkflowIdRoute: typeof SettingsWorkflowManagerWorkflowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailers/': {
      id: '/retailers/'
      path: '/retailers'
      fullPath: '/retailers/'
      preLoaderRoute: typeof RetailersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/': {
      id: '/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailers/$retailerId': {
      id: '/retailers/$retailerId'
      path: '/retailers/$retailerId'
      fullPath: '/retailers/$retailerId'
      preLoaderRoute: typeof RetailersRetailerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/workflow-manager/$workflowId': {
      id: '/settings/workflow-manager/$workflowId'
      path: '/settings/workflow-manager/$workflowId'
      fullPath: '/settings/workflow-manager/$workflowId'
      preLoaderRoute: typeof SettingsWorkflowManagerWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/preview/$formId': {
      id: '/forms/preview/$formId'
      path: '/forms/preview/$formId'
      fullPath: '/forms/preview/$formId'
      preLoaderRoute: typeof FormsPreviewFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/fill/$formSlug': {
      id: '/forms/fill/$formSlug'
      path: '/forms/fill/$formSlug'
      fullPath: '/forms/fill/$formSlug'
      preLoaderRoute: typeof FormsFillFormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/builder/$formId': {
      id: '/forms/builder/$formId'
      path: '/forms/builder/$formId'
      fullPath: '/forms/builder/$formId'
      preLoaderRoute: typeof FormsBuilderFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/submissions': {
      id: '/forms/$formId/submissions'
      path: '/forms/$formId/submissions'
      fullPath: '/forms/$formId/submissions'
      preLoaderRoute: typeof FormsFormIdSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/share': {
      id: '/forms/$formId/share'
      path: '/forms/$formId/share'
      fullPath: '/forms/$formId/share'
      preLoaderRoute: typeof FormsFormIdShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/analytics': {
      id: '/forms/$formId/analytics'
      path: '/forms/$formId/analytics'
      fullPath: '/forms/$formId/analytics'
      preLoaderRoute: typeof FormsFormIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  RetailersRetailerIdRoute: RetailersRetailerIdRoute,
  FormsIndexRoute: FormsIndexRoute,
  RetailersIndexRoute: RetailersIndexRoute,
  FormsFormIdAnalyticsRoute: FormsFormIdAnalyticsRoute,
  FormsFormIdShareRoute: FormsFormIdShareRoute,
  FormsFormIdSubmissionsRoute: FormsFormIdSubmissionsRoute,
  FormsBuilderFormIdRoute: FormsBuilderFormIdRoute,
  FormsFillFormSlugRoute: FormsFillFormSlugRoute,
  FormsPreviewFormIdRoute: FormsPreviewFormIdRoute,
  SettingsWorkflowManagerWorkflowIdRoute:
    SettingsWorkflowManagerWorkflowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
